### ISSUE TITLE
Problem z verification_token

### ISSUE THREAD

**Issue by atuis** [apqlzm/luxhunter#3]
Wywala mi się na:

Traceback (most recent call last):
  File "./luxhunter.py", line 186, in <module>
    main()
  File "./luxhunter.py", line 180, in main
    isav = find(session, service_id=args.serviceid, date_from=args.datefrom, date_to=args.dateto, doctor_id=args.doctorid, city_id=args.cityid, clinic_id=args.clinicid, time_option=args.timeoption)
  File "./luxhunter.py", line 122, in find
    search_params['__RequestVerificationToken'] = verification_token[0]
IndexError: list index out of range

Skrypt nie znajduje
'//form/input[@name="__RequestVerificationToken"]/@value' 
na stronie
main_page_url = 'https://portalpacjenta.luxmed.pl/PatientPortal/'
i nie przypisuje żadnej wartości do verification_token

Coś się pozmieniało w luxmed, czy ja coś źle robię?
Z góry dziękuję.

**Comment by apqlzm** [comment]
Grubo ponad rok nie logowałem się do Luxmedu (obecnie korzystam z Medicoveru). Wygląda na to że skrypt się lekko zdezaktualizował. Spróbuję zerknąć na niego w najbliższy weekend.

**Comment by atuis** [comment]
Dzięki, już sobie poradziłem. Trzeba było tylko zmodyfikować link w skrypcie, bo obecnie formularz nie jest dostępny od razu po zalogowaniu, ale schowany trochę głębiej.
Dokładnie zmieniłem to:
main_page_url = 'https://portalpacjenta.luxmed.pl/PatientPortal/Reservations/Coordination/Activity?actionId=90'

**Comment by apqlzm** [comment]
Obawiam się że to nie załatwia sprawy. Sporo się zmieniło w Luxmedzie wprowadzili m. in. reCaptcha. Metoda is_appointment_available zwraca fałszywą informację że znaleziono wizytę.
